#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo "🔍 Checando código com ESLint e Prettier..."
npm run lint:fix
npm run format:fix

if [ $? -ne 0 ]; then
  echo "❌ ESLint ou Prettier encontrou erros. Commit cancelado."
  exit 1
fi

echo "✅ Código formatado com sucesso!"
